services:
  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: sheduled-reports-app
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_LEVEL: debug
      GF_DEFAULT_APP_MODE: development
      GF_PLUGIN_APP_DATA_PATH: /var/lib/grafana/plugin-data
      GF_INSTALL_PLUGINS: ""
      # Enable managed service accounts for app plugins (Grafana 10.3+)
      GF_FEATURE_TOGGLES_ENABLE: externalServiceAccounts
      GF_AUTH_MANAGED_SERVICE_ACCOUNTS_ENABLED: true
      NO_PROXY: "localhost,127.0.0.1,localaddress,.localdomain.com,10.233.1.0/24,renderer,grafana"
      no_proxy: "localhost,127.0.0.1,localaddress,.localdomain.com,10.233.1.0/24,renderer,grafana"
      GF_SMTP_ENABLED: true
      GF_SMTP_HOST: ${GF_SMTP_HOST:-smtp.example.com:25}
      GF_SMTP_USER: ${GF_SMTP_USER:-}
      GF_SMTP_PASSWORD: ${GF_SMTP_PASSWORD:-}
      GF_SMTP_FROM_ADDRESS: ${GF_SMTP_FROM_ADDRESS:-noreply@example.com}
      GF_SMTP_FROM_NAME: ${GF_SMTP_FROM_NAME:-Grafana Reports}
      GF_SMTP_SKIP_VERIFY: true
    volumes:
      - ./dist:/var/lib/grafana/plugins/sheduled-reports-app
      - grafana-storage:/var/lib/grafana
    depends_on:
      - renderer

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "8081:8081"
    environment:
      ENABLE_METRICS: true
      LOG_LEVEL: debug
      HTTP_PORT: 8081
      IGNORE_HTTPS_ERRORS: true
      NO_PROXY: "localhost,127.0.0.1,grafana"
      no_proxy: "localhost,127.0.0.1,grafana"
      RENDERING_MODE: default
      RENDERING_ARGS: "--no-sandbox,--disable-gpu"

volumes:
  grafana-storage:
